### PR TITLE
Setup winxed

### PR DESCRIPTION
**Pull request by lateau**
I'm so late, because I had a high fever.

setup.winxed allows almost targets of setup.pir.
'smoke' and 'test' works but not fully, because seems like WINXED does not allows named parmeters in pir.
so 'runtests' cannot be called and it causes 'no test'.
I'm not sure it's bug but I'll report it to NotFound then modify this problems.

And some codes are very dirty but they will be fixed.

$ winxed --version
1.2.0
$ winxed setup.winxed test
.......
.......

Files=28, Tests=0,  0.172 wallclock secs                 <<<<<< HERE, "Tests=0"
Result: FAIL
creat report.tar.gz

### CODE REVIEW

**Comment by NotFound** [comment]
Winxed pirops are not, and will never be, a generic inlining pir feature. They don't expect pir sintactic sugar, just take an op and its operands, and the operands are winxed expressions.

All parrot calling conventions are supported via modifiers in parameters and arguments. No pir required.

**Comment by leto** [comment]
@NotFound: can you help refactor this so the smoke and test targets work? I don't have the tuits.

**Comment by NotFound** [comment]
Fixed and added in the branch winxed_setup, 3f3b4a75ad

**Comment by lateau** [comment]
setup.winxed is tested with winxed1.2.0 and works now.
I found a way from comments of NotFound to me.
I tested the builder on fedora15 amd64 and osx10.7 only, so more tests are needed on some other machine.

many thanks:
@leto
@NotFound

**Comment by leto** [comment]
This looks good. Is there a reason the POD is commented out?

**Comment by lateau** [comment]
Because I got a error message with pod in winxed "setup.winxed:3: Unexpected token near =".
And I cannot found any informations of pod with winxed at these pages:

http://winxed.org/
http://whiteknight.github.com/Rosella/winxed/index.html

Anyway, If we can use pod for some informations in winxed, that's much pretty better than some others.

**Comment by leto** [comment]
Wrapping the POD in a multi-line comment block with /\* and */ will probably
make Winxed ignore it, but you will still be able to run perldoc on the file.

**Comment by lateau** [comment]
much better!

@leto++

**Comment by lateau** [comment]
not merged. is NotFound doing this?

_Sent via Hubroid_

**Comment by leto** [comment]
Accidentally closed this before, without pressing the shiny merge button first.

**Pull request merged**
