### PR TITLE
new methods

### PR DESCRIPTION
**Pull request by lateau**
- Float#==
- Float#===
- Float#eql?

### CODE REVIEW

**Comment by tadzik** [comment]
The tests fail on my box:

┌─[tadzik@yavin4]─[~/src/cardinal](lateau-lib191)
└─[%]─> ./installable_cardinal t/float/eql.t
1..2
Class 'CardinalFloat' not found
current instr.: '_block11' pc 86 ((file unknown):40)
called from Sub 'cardinal;PCT;HLLCompiler;eval' pc 1134 (compilers/pct/src/PCT/HLLCompiler.pir:597)
called from Sub 'cardinal;PCT;HLLCompiler;evalfiles' pc 1501 (compilers/pct/src/PCT/HLLCompiler.pir:764)
called from Sub 'cardinal;PCT;HLLCompiler;command_line' pc 1719 (compilers/pct/src/PCT/HLLCompiler.pir:875)
called from Sub 'cardinal;cardinal;Compiler;main' pc 78972 (src/gen_grammar.pir:5369)

┌─[tadzik@yavin4]─[~/src/cardinal](lateau-lib191)
└─[%]─> ./installable_cardinal t/float/flo_eq.t
1..5
Class 'CardinalFloat' not found
current instr.: '_block11' pc 86 ((file unknown):40)
called from Sub 'cardinal;PCT;HLLCompiler;eval' pc 1134 (compilers/pct/src/PCT/HLLCompiler.pir:597)
called from Sub 'cardinal;PCT;HLLCompiler;evalfiles' pc 1501 (compilers/pct/src/PCT/HLLCompiler.pir:764)
called from Sub 'cardinal;PCT;HLLCompiler;command_line' pc 1719 (compilers/pct/src/PCT/HLLCompiler.pir:875)
called from Sub 'cardinal;cardinal;Compiler;main' pc 78972 (src/gen_grammar.pir:5369)

**Comment by qiuhw** [comment]
Since my last commit has been merged into the repository, the error message of "Class 'CardinalFloat' not found" shouldn't happen again, I think, although I didn't test this commit of lateau's.

**Comment by lateau** [comment]
oops. i did this again.
setup.pir did not have CardinalFloat as their build target.
modified and I've pushed. each tests of rake and setup.pir are passed now.

$ parrot setup.pir clean; parrot setup.pir test
...
t/float/eql.t .................. ok
t/float/flo_eq.t ............... ok
t/float/to_f.t ................. ok
t/float/zero.t ................. ok
...

$ rake clean; rake test:float:all
...
/Users/lateau/.local/src/parrot/parrot-3.3.0/parrot cardinal.pbc --target=pir -o t/float/gen_zero.pir t/float/zero.t
Running test:float:zero 2 tests... 2 ok 0 not ok
/Users/lateau/.local/src/parrot/parrot-3.3.0/parrot cardinal.pbc --target=pir -o t/float/gen_eql.pir t/float/eql.t
Running test:float:eql 2 tests... 2 ok 0 not ok
/Users/lateau/.local/src/parrot/parrot-3.3.0/parrot cardinal.pbc --target=pir -o t/float/gen_flo_eq.pir t/float/flo_eq.t
Running test:float:flo_eq 6 tests... 6 ok 0 not ok
...

**Comment by tadzik** [comment]
Looks good now, thanks

**Pull request merged**
