### PR TITLE
add tests & update informations

### PR DESCRIPTION
**Pull request by lateau**

### CODE REVIEW

**Comment by leto** [comment]
Did this get lost or was it merged in a different pull request?

**Comment by lateau** [comment]
not merged yet :)
In this time, "States & Graphs" show you how master & forks going on.
the button is top-right on this page.

thanks

**Comment by leto** [comment]
@lateau does "rake test:all" pass for you with this patch? I am seeing cardinal fail (without this patch) like this:

```
/Users/leto/git/parrot/parrot cardinal.pbc --target=pir -o t/gen_01-stmts.pir t/01-stmts.t
Syntax error at line 97, near "(\n-\n1\n)\npu"

current instr.: 'cardinal;PGE;Util;die' pc 135 (runtime/parrot/library/PGE/Util.pir:86)
called from Sub 'cardinal;cardinal;Grammar;TOP' pc 13762 (src/classes/Array.pir:158)
called from Sub 'cardinal;PCT;HLLCompiler;parse' pc 826 (compilers/pct/src/PCT/HLLCompiler.pir:463)
called from Sub 'cardinal;PCT;HLLCompiler;compile' pc 464 (compilers/pct/src/PCT/HLLCompiler.pir:331)
called from Sub 'cardinal;PCT;HLLCompiler;eval' pc 1081 (compilers/pct/src/PCT/HLLCompiler.pir:582)
called from Sub 'cardinal;PCT;HLLCompiler;evalfiles' pc 1501 (compilers/pct/src/PCT/HLLCompiler.pir:764)
called from Sub 'cardinal;PCT;HLLCompiler;command_line' pc 1726 (compilers/pct/src/PCT/HLLCompiler.pir:879)
called from Sub 'cardinal;cardinal;Compiler;main' pc 79828 (src/gen_grammar.pir:105) (src/parser/actions.pm:1)
Running test:stmts Complete failure... failed to compile.
```

**Comment by lateau** [comment]
@leto 

the tests expected to fail for basic implements, but raise parse error is not good.
ok, I'll work around this parse problems.

**Comment by lateau** [comment]
@leto

I'm doing analyzing ruby parser these days and I think our parser is needed to behave more ruby like. many changes will be needed and I have so much time work around it. my work will takes much time so I close this request in this time. thank you.

**Pull request closed without merging**
